// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exfvnhqwalpejnbxapwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZnZuaHF3YWxwZWpuYnhhcHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjAwMjUsImV4cCI6MjA2NTg5NjAyNX0._K2EdzNf8nAxtqJr4rrEUb5zWUeRt8BS2D8w8pawv00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);